export * from './Slider/Slider';
export * from './Questions/Questions';
export * from './Quiz/Quiz';
export * from './Form/Form';
export * from './PageTitle/PageTitle';
export * from './Catalog/Catalog';
export * from './CardReviews/CardReviews';
export * from './CardVideo/CardVideo';
export * from './WhyChoose/WhyChoose';